//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeyazEsya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BeyazEsya()
        {
            this.BulasikMakinesis = new HashSet<BulasikMakinesi>();
            this.Buzdolabis = new HashSet<Buzdolabi>();
            this.CamasirMakinesis = new HashSet<CamasirMakinesi>();
            this.DerinDondurucus = new HashSet<DerinDondurucu>();
            this.Fırın = new HashSet<Fırın>();
        }
    
        public int BeyazEsyaID { get; set; }
        public string BeyazEsyaTuru { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> KategoriID { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Urunler Urunler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BulasikMakinesi> BulasikMakinesis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buzdolabi> Buzdolabis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamasirMakinesi> CamasirMakinesis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DerinDondurucu> DerinDondurucus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fırın> Fırın { get; set; }
    }
}
