//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sipari
    {
        public int SiparisID { get; set; }
        public string SiparisAdi { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> UrunID { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
