//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Televizyon
    {
        public int TelevizyonID { get; set; }
        public string Markasi { get; set; }
        public string Modeli { get; set; }
        public string CikisYili { get; set; }
        public string TahminiFiyatAraligi { get; set; }
        public string Ekran { get; set; }
        public string EkranBoyutu { get; set; }
        public string EkranCozunurlugu { get; set; }
        public string SesCıkısGucu { get; set; }
        public string EnerjiTuketimSinifi { get; set; }
        public string DahiliWiFi { get; set; }
        public Nullable<int> GoruntuID { get; set; }
    
        public virtual Goruntu Goruntu { get; set; }
    }
}
