//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Telefon()
        {
            this.AkilliTelefons = new HashSet<AkilliTelefon>();
            this.TusluTelefons = new HashSet<TusluTelefon>();
        }
    
        public int TelefonID { get; set; }
        public string TelefonTuru { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> KategoriID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AkilliTelefon> AkilliTelefons { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Urunler Urunler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TusluTelefon> TusluTelefons { get; set; }
    }
}
