//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _FacadeSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        public int CreditID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
    }
}
