//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UrunBilgiEntities : DbContext
    {
        public UrunBilgiEntities()
            : base("name=UrunBilgiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AkilliTelefon> AkilliTelefons { get; set; }
        public virtual DbSet<BeyazEsya> BeyazEsyas { get; set; }
        public virtual DbSet<Bilgisayar> Bilgisayars { get; set; }
        public virtual DbSet<BulasikMakinesi> BulasikMakinesis { get; set; }
        public virtual DbSet<Buzdolabi> Buzdolabis { get; set; }
        public virtual DbSet<CamasirMakinesi> CamasirMakinesis { get; set; }
        public virtual DbSet<DerinDondurucu> DerinDondurucus { get; set; }
        public virtual DbSet<Fırın> Fırın { get; set; }
        public virtual DbSet<Goruntu> Goruntus { get; set; }
        public virtual DbSet<Kategoriler> Kategorilers { get; set; }
        public virtual DbSet<Kullanici> Kullanicis { get; set; }
        public virtual DbSet<Laptop> Laptops { get; set; }
        public virtual DbSet<MasaüstüBilgisayar> MasaüstüBilgisayar { get; set; }
        public virtual DbSet<Monitor> Monitors { get; set; }
        public virtual DbSet<Musteri> Musteris { get; set; }
        public virtual DbSet<Sipari> Siparis { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tablet> Tablets { get; set; }
        public virtual DbSet<Telefon> Telefons { get; set; }
        public virtual DbSet<Televizyon> Televizyons { get; set; }
        public virtual DbSet<TusluTelefon> TusluTelefons { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
    }
}
